<?php

/* 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 */

$numbers = [1,2];
$last_number = end($numbers);
while($last_number<4000000) {
	$last_key		= key($numbers);
	$numbers[]		= $numbers[$last_key] + $numbers[$last_key-1];
	$last_number	= end($numbers);
}
echo array_sum(array_filter($numbers, function($number) { return ($number %2===0);}));